### ISSUE TITLE
Violation of GPLv3

### ISSUE THREAD

**Issue by cyberknight777** [Anonynusman/psFconsole#6]
Here's the original repository: https://github.com/abhackerofficial/pentesting-framework

Your repository will be reported as for violating the licensing (GPLv3) as per Section 4, Section 5 and Section 11 of the [GNU GPL Licensing](https://www.gnu.org/licenses/gpl-3.0.en.html). 

Do not kang code which is not yours.

**Comment by PeroSar** [comment]
yes

**Comment by PeroSar** [comment]
fait hard

**Comment by MisanthropyDK** [comment]
Fuck people from ghana

**Comment by PeroSar** [comment]
![20210617_201220](https://user-images.githubusercontent.com/85673786/122872773-8e1b5d80-d34e-11eb-9d6e-edcf6fd52820.jpg)
Repository owner spotted

**Comment by MisanthropyDK** [comment]
> ![20210617_201220](https://user-images.githubusercontent.com/85673786/122872773-8e1b5d80-d34e-11eb-9d6e-edcf6fd52820.jpg)
> Repository owner spotted

Ahhh this beach

**Comment by PeroSar** [comment]
> > ![20210617_201220](https://user-images.githubusercontent.com/85673786/122872773-8e1b5d80-d34e-11eb-9d6e-edcf6fd52820.jpg)
> > Repository owner spotted
> 
> Ahhh this beach

Lmao

**Comment by MisanthropyDK** [comment]
> > Ahhh this beach
> 
> Lmao

This guy gonna soon heck the world by copying other's repo and using them
