### ISSUE TITLE
hello retarded anusman

### ISSUE THREAD

**Issue by PeroSar** [Anonynusman/psFconsole#8]
retarded anusman

**Comment by MisanthropyDK** [comment]
Naah he is Mohammed the bomber

**Comment by PeroSar** [comment]
> Naah he is Mohammed the bomber

💣

**Comment by MisanthropyDK** [comment]
> > Naah he is Mohammed the bomber
> 
> 💣

Rip for now

**Comment by 0n1cOn3** [comment]
Guys, thats a reason for banning you from Github. Delete this @PeroSar

**Comment by PeroSar** [comment]
> Guys, thats a reason for banning you from Github. Delete this @PeroSar

k
